@_ = User.create!  name: "",
  password: "password",
  password_confirmation: "password",
  email: "zeljko@z-ware.fi",
  nationality: "",
  club: ""
@katariina_puolakanaho_finland = User.create!  name: "Katariina Puolakanaho",
  password: "password",
  password_confirmation: "password",
  email: "kata@iloisettassut.fi",
  nationality: "finland",
  club: ""
@toni_parkkinen_finland = User.create!  name: "Toni Parkkinen",
  password: "password",
  password_confirmation: "password",
  email: "t.j.parkkinen@gmail.com",
  nationality: "finland",
  club: ""
@antti_makiaho_finland = User.create!  name: "Antti Mäkiaho",
  password: "password",
  password_confirmation: "password",
  email: "antti.mäkiaho@example.com",
  nationality: "finland",
  club: ""
@igor_tracz_poland = User.create!  name: "Igor Tracz",
  password: "password",
  password_confirmation: "password",
  email: "igor.tracz@example.com",
  nationality: "poland",
  club: ""
@essi_hytonen_finland = User.create!  name: "Essi Hytönen",
  password: "password",
  password_confirmation: "password",
  email: "essi.hytönen@example.com",
  nationality: "finland",
  club: ""
@elin_bjork_sweden = User.create!  name: "Elin Björk",
  password: "password",
  password_confirmation: "password",
  email: "elin.björk@example.com",
  nationality: "sweden",
  club: ""
@renata_v_lkov_czechrepublic = User.create!  name: "Renata Válková",
  password: "password",
  password_confirmation: "password",
  email: "renata.válková@example.com",
  nationality: "czechrepublic",
  club: ""
@agnieszka_rychwalska_poland = User.create!  name: "Agnieszka Rychwalska",
  password: "password",
  password_confirmation: "password",
  email: "agnieszka.rychwalska@example.com",
  nationality: "poland",
  club: ""
@mikael_hogberg_sweden = User.create!  name: "Mikael Högberg",
  password: "password",
  password_confirmation: "password",
  email: "mikael.högberg@example.com",
  nationality: "sweden",
  club: ""
@catarina_sodersten_sweden = User.create!  name: "Catarina Södersten",
  password: "password",
  password_confirmation: "password",
  email: "catarina.södersten@example.com",
  nationality: "sweden",
  club: ""
@herbert_hiermeier_germany = User.create!  name: "Herbert Hiermeier",
  password: "password",
  password_confirmation: "password",
  email: "herbert.hiermeier@example.com",
  nationality: "germany",
  club: ""
@krisztianroland_kiss_norway = User.create!  name: "KrisztianRoland Kiss",
  password: "password",
  password_confirmation: "password",
  email: "krisztianroland.kiss@example.com",
  nationality: "norway",
  club: ""
@sussie_gronberg_sweden = User.create!  name: "Sussie Grönberg",
  password: "password",
  password_confirmation: "password",
  email: "sussie.grönberg@example.com",
  nationality: "sweden",
  club: ""
@heta_lehtomaki_finland = User.create!  name: "Heta Lehtomäki",
  password: "password",
  password_confirmation: "password",
  email: "heta.lehtomäki@example.com",
  nationality: "finland",
  club: ""
@lukasz_paczynski_poland = User.create!  name: "Lukasz Paczynski",
  password: "password",
  password_confirmation: "password",
  email: "lukasz.paczynski@example.com",
  nationality: "poland",
  club: ""
@dagmar_nesnerov_czechrepublic = User.create!  name: "Dagmar Nesnerová",
  password: "password",
  password_confirmation: "password",
  email: "dagmar.nesnerová@example.com",
  nationality: "czechrepublic",
  club: ""
@anu_parikka_finland = User.create!  name: "Anu Parikka",
  password: "password",
  password_confirmation: "password",
  email: "anu.parikka@example.com",
  nationality: "finland",
  club: ""
@susanna_bürkland_finland = User.create!  name: "Susanna Bürkland",
  password: "password",
  password_confirmation: "password",
  email: "susanna.bürkland@example.com",
  nationality: "finland",
  club: ""
@martins_kristons_latvia = User.create!  name: "Martins Kristons",
  password: "password",
  password_confirmation: "password",
  email: "martins.kristons@example.com",
  nationality: "latvia",
  club: ""
@alain_hercher_france = User.create!  name: "Alain Hercher",
  password: "password",
  password_confirmation: "password",
  email: "alain.hercher@example.com",
  nationality: "france",
  club: ""
@tuomas_notko_finland = User.create!  name: "Tuomas Notko",
  password: "password",
  password_confirmation: "password",
  email: "tuomas.notko@example.com",
  nationality: "finland",
  club: ""
@pavel_otbetkin_russia = User.create!  name: "Pavel Otbetkin",
  password: "password",
  password_confirmation: "password",
  email: "pavel.otbetkin@example.com",
  nationality: "russia",
  club: ""
@slavomir_pavlik_czechrepublic = User.create!  name: "Slavomir Pavlik",
  password: "password",
  password_confirmation: "password",
  email: "slavomir.pavlik@example.com",
  nationality: "czechrepublic",
  club: ""
@julieboysen_hillestad_norway = User.create!  name: "JulieBoysen Hillestad",
  password: "password",
  password_confirmation: "password",
  email: "julieboysen.hillestad@example.com",
  nationality: "norway",
  club: ""
@axel_coste_france = User.create!  name: "Axel Coste",
  password: "password",
  password_confirmation: "password",
  email: "axel.coste@example.com",
  nationality: "france",
  club: ""
@vilma_laitinen_finland = User.create!  name: "Vilma Laitinen",
  password: "password",
  password_confirmation: "password",
  email: "vilma.laitinen@example.com",
  nationality: "finland",
  club: ""
@kimmo_hytonen_finland = User.create!  name: "Kimmo Hytönen",
  password: "password",
  password_confirmation: "password",
  email: "kimmo.hytönen@example.com",
  nationality: "finland",
  club: ""
@conny_toyra_sweden = User.create!  name: "Conny Töyrä",
  password: "password",
  password_confirmation: "password",
  email: "conny.töyrä@example.com",
  nationality: "sweden",
  club: ""
@teemu_kaivola_finland = User.create!  name: "Teemu Kaivola",
  password: "password",
  password_confirmation: "password",
  email: "teemu.kaivola@example.com",
  nationality: "finland",
  club: ""
@trine_olsen_norway = User.create!  name: "Trine Olsen",
  password: "password",
  password_confirmation: "password",
  email: "trine.olsen@example.com",
  nationality: "norway",
  club: ""
@riitta_kempe_finland = User.create!  name: "Riitta Kempe",
  password: "password",
  password_confirmation: "password",
  email: "riitta.kempe@example.com",
  nationality: "finland",
  club: ""
@vesa_pekka_lehtomaki_finland = User.create!  name: "Vesa-Pekka Lehtomäki",
  password: "password",
  password_confirmation: "password",
  email: "vesa-pekka.lehtomäki@example.com",
  nationality: "finland",
  club: ""
@jirí_trnka_czechrepublic = User.create!  name: "Jirí Trnka",
  password: "password",
  password_confirmation: "password",
  email: "jirí.trnka@example.com",
  nationality: "czechrepublic",
  club: ""
@jenni_kreivi_finland = User.create!  name: "Jenni Kreivi",
  password: "password",
  password_confirmation: "password",
  email: "jenni.kreivi@example.com",
  nationality: "finland",
  club: ""
@indre_daujotiene_lithuania = User.create!  name: "Indre Daujotiene",
  password: "password",
  password_confirmation: "password",
  email: "indre.daujotiene@example.com",
  nationality: "lithuania",
  club: ""
@michael_beck_germany = User.create!  name: "Michael Beck",
  password: "password",
  password_confirmation: "password",
  email: "michael.beck@example.com",
  nationality: "germany",
  club: ""
@montse_claverol_spain = User.create!  name: "Montse Claverol",
  password: "password",
  password_confirmation: "password",
  email: "montse.claverol@example.com",
  nationality: "spain",
  club: ""
@michael_chovanec_czechrepublic = User.create!  name: "Michael Chovanec",
  password: "password",
  password_confirmation: "password",
  email: "michael.chovanec@example.com",
  nationality: "czechrepublic",
  club: ""
@anna_bajer_poland = User.create!  name: "Anna Bajer",
  password: "password",
  password_confirmation: "password",
  email: "anna.bajer@example.com",
  nationality: "poland",
  club: ""
@anttoni_tolvi_finland = User.create!  name: "Anttoni Tolvi",
  password: "password",
  password_confirmation: "password",
  email: "anttoni.tolvi@example.com",
  nationality: "finland",
  club: ""
@pasi_heinonen_finland = User.create!  name: "Pasi Heinonen",
  password: "password",
  password_confirmation: "password",
  email: "pasi.heinonen@example.com",
  nationality: "finland",
  club: ""
@riku_setala_finland = User.create!  name: "Riku Setälä",
  password: "password",
  password_confirmation: "password",
  email: "riku.setälä@example.com",
  nationality: "finland",
  club: ""
@alexandra_kathan_germany = User.create!  name: "Alexandra Kathan",
  password: "password",
  password_confirmation: "password",
  email: "alexandra.kathan@example.com",
  nationality: "germany",
  club: ""
@carl_johan_waller_sweden = User.create!  name: "Carl-Johan Waller",
  password: "password",
  password_confirmation: "password",
  email: "carl-johan.waller@example.com",
  nationality: "sweden",
  club: ""
@michael_tetzner_germany = User.create!  name: "Michael Tetzner",
  password: "password",
  password_confirmation: "password",
  email: "michael.tetzner@example.com",
  nationality: "germany",
  club: ""
@ville_halme_finland = User.create!  name: "Ville Halme",
  password: "password",
  password_confirmation: "password",
  email: "ville.halme@example.com",
  nationality: "finland",
  club: ""
@eduard_grobinsch_latvia = User.create!  name: "Eduard Grobinsch",
  password: "password",
  password_confirmation: "password",
  email: "eduard.grobinsch@example.com",
  nationality: "latvia",
  club: ""
@sophie_verla_hungary = User.create!  name: "Sophie Verla",
  password: "password",
  password_confirmation: "password",
  email: "sophie.verla@example.com",
  nationality: "hungary",
  club: ""
@maciej_tomaszewski_poland = User.create!  name: "Maciej Tomaszewski",
  password: "password",
  password_confirmation: "password",
  email: "maciej.tomaszewski@example.com",
  nationality: "poland",
  club: ""
@kaisa_lehto_finland = User.create!  name: "Kaisa Lehto",
  password: "password",
  password_confirmation: "password",
  email: "kaisa.lehto@example.com",
  nationality: "finland",
  club: ""
@frode_haugan_norway = User.create!  name: "Frode Haugan",
  password: "password",
  password_confirmation: "password",
  email: "frode.haugan@example.com",
  nationality: "norway",
  club: ""
@aleksandr_moskvichev_russia = User.create!  name: "Aleksandr Moskvichev",
  password: "password",
  password_confirmation: "password",
  email: "aleksandr.moskvichev@example.com",
  nationality: "russia",
  club: ""
@jos_broers_netherlands = User.create!  name: "Jos Broers",
  password: "password",
  password_confirmation: "password",
  email: "jos.broers@example.com",
  nationality: "netherlands",
  club: ""
@hege_ingerigtsen_norway = User.create!  name: "Hege Ingerigtsen",
  password: "password",
  password_confirmation: "password",
  email: "hege.ingerigtsen@example.com",
  nationality: "norway",
  club: ""
@kurt_zwingli_switzerland = User.create!  name: "Kurt Zwingli",
  password: "password",
  password_confirmation: "password",
  email: "kurt.zwingli@example.com",
  nationality: "switzerland",
  club: ""
@tamara_schlemmer_germany = User.create!  name: "Tamara Schlemmer",
  password: "password",
  password_confirmation: "password",
  email: "tamara.schlemmer@example.com",
  nationality: "germany",
  club: ""
@ari_laitinen_finland = User.create!  name: "Ari Laitinen",
  password: "password",
  password_confirmation: "password",
  email: "ari.laitinen@example.com",
  nationality: "finland",
  club: ""
@klaus_starflinger_germany = User.create!  name: "Klaus Starflinger",
  password: "password",
  password_confirmation: "password",
  email: "klaus.starflinger@example.com",
  nationality: "germany",
  club: ""
@cari_rorstrom_sweden = User.create!  name: "Cari Rörström",
  password: "password",
  password_confirmation: "password",
  email: "cari.rörström@example.com",
  nationality: "sweden",
  club: ""
@remy_coster_france = User.create!  name: "Remy Coster",
  password: "password",
  password_confirmation: "password",
  email: "remy.coster@example.com",
  nationality: "france",
  club: ""
@alister_dunlop_scotland = User.create!  name: "Alister Dunlop",
  password: "password",
  password_confirmation: "password",
  email: "alister.dunlop@example.com",
  nationality: "scotland",
  club: ""
@panu_sipila_finland = User.create!  name: "Panu Sipilä",
  password: "password",
  password_confirmation: "password",
  email: "panu.sipilä@example.com",
  nationality: "finland",
  club: ""
@rudi_ropertz_germany = User.create!  name: "Rudi Ropertz",
  password: "password",
  password_confirmation: "password",
  email: "rudi.ropertz@example.com",
  nationality: "germany",
  club: ""
@pavel_pfeifer_czechrepublic = User.create!  name: "Pavel Pfeifer",
  password: "password",
  password_confirmation: "password",
  email: "pavel.pfeifer@example.com",
  nationality: "czechrepublic",
  club: ""
@pauliina_kiiski_finland = User.create!  name: "Pauliina Kiiski",
  password: "password",
  password_confirmation: "password",
  email: "pauliina.kiiski@example.com",
  nationality: "finland",
  club: ""
@julia_johansson_sweden = User.create!  name: "Julia Johansson",
  password: "password",
  password_confirmation: "password",
  email: "julia.johansson.com@example.com",
  nationality: "sweden",
  club: ""
@aleksandr_stoliarov_russia = User.create!  name: "Aleksandr Stoliarov",
  password: "password",
  password_confirmation: "password",
  email: "aleksandr.stoliarov@example.com",
  nationality: "russia",
  club: ""
@martin_vrtel_czechrepublic = User.create!  name: "Martin Vrtel",
  password: "password",
  password_confirmation: "password",
  email: "martin.vrtel@example.com",
  nationality: "czechrepublic",
  club: ""
@grzegorz_burzynski_poland = User.create!  name: "Grzegorz Burzynski",
  password: "password",
  password_confirmation: "password",
  email: "grzegorz.burzynski@example.com",
  nationality: "poland",
  club: ""
@horst_maas_austria = User.create!  name: "Horst Maas",
  password: "password",
  password_confirmation: "password",
  email: "horst.maas@example.com",
  nationality: "austria",
  club: ""
@johan_sernheim_sweden = User.create!  name: "Johan Sernheim",
  password: "password",
  password_confirmation: "password",
  email: "johan.sernheim@example.com",
  nationality: "sweden",
  club: ""
@joni_elomaa_finland = User.create!  name: "Joni Elomaa",
  password: "password",
  password_confirmation: "password",
  email: "joni.elomaa@example.com",
  nationality: "finland",
  club: ""
@kati_kumpulainen_finland = User.create!  name: "Kati Kumpulainen",
  password: "password",
  password_confirmation: "password",
  email: "kati.kumpulainen@example.com",
  nationality: "finland",
  club: ""
@suvi_lahtinen_finland = User.create!  name: "Suvi Lahtinen",
  password: "password",
  password_confirmation: "password",
  email: "suvi.lahtinen@example.com",
  nationality: "finland",
  club: ""
@gregor_zdenek_czechrepublic = User.create!  name: "Gregor Zdenek",
  password: "password",
  password_confirmation: "password",
  email: "gregor.zdenek@example.com",
  nationality: "czechrepublic",
  club: ""
@pia_alpua_finland = User.create!  name: "Pia Alpua",
  password: "password",
  password_confirmation: "password",
  email: "pia.alpua@example.com",
  nationality: "finland",
  club: ""
@vesa_pekka_jurvelin_finland = User.create!  name: "Vesa-Pekka Jurvelin",
  password: "password",
  password_confirmation: "password",
  email: "vesa-pekka.jurvelin@example.com",
  nationality: "finland",
  club: "rpkk"
@maija_nivala_finland = User.create!  name: "Maija Nivala",
  password: "password",
  password_confirmation: "password",
  email: "maija.nivala@example.com",
  nationality: "finland",
  club: "rpkk"
@samuli_nissinen_finland = User.create!  name: "Samuli Nissinen",
  password: "password",
  password_confirmation: "password",
  email: "samuli.nissinen@example.com",
  nationality: "finland",
  club: "kpsh"
@marika_tiiperi_finland = User.create!  name: "Marika Tiiperi",
  password: "password",
  password_confirmation: "password",
  email: "marika.tiiperi@example.com",
  nationality: "finland",
  club: "rpkk"
@teemu_lojamo_finland = User.create!  name: "Teemu Lojamo",
  password: "password",
  password_confirmation: "password",
  email: "teemu.lojamo@example.com",
  nationality: "finland",
  club: "kvks"
@maria_viitahalme_finland = User.create!  name: "Maria Viitahalme",
  password: "password",
  password_confirmation: "password",
  email: "maria.viitahalme@example.com",
  nationality: "finland",
  club: "kvks"
@marko_viitahalme_finland = User.create!  name: "Marko Viitahalme",
  password: "password",
  password_confirmation: "password",
  email: "marko.viitahalme@example.com",
  nationality: "finland",
  club: "kvks"
@raisa_heiskanen_finland = User.create!  name: "Raisa Heiskanen",
  password: "password",
  password_confirmation: "password",
  email: "raisa.heiskanen@example.com",
  nationality: "finland",
  club: "kvks"
@eija_juntika_finland = User.create!  name: "Eija Juntika",
  password: "password",
  password_confirmation: "password",
  email: "eija.juntika@example.com",
  nationality: "finland",
  club: "kvks"
@tiina_hakala_finland = User.create!  name: "Tiina Hakala",
  password: "password",
  password_confirmation: "password",
  email: "tiina.hakala@example.com",
  nationality: "finland",
  club: "l-svu"
@sanna_polso_finland = User.create!  name: "Sanna Polso",
  password: "password",
  password_confirmation: "password",
  email: "sanna.polso@example.com",
  nationality: "finland",
  club: "sisuva"
@katariina_puolakanaho_finland = User.create!  name: "Katariina Puolakanaho",
  password: "password",
  password_confirmation: "password",
  email: "katariina.puolakanaho@example.com",
  nationality: "finland",
  club: "l-svu"
@anu_jaakonsaari_finland = User.create!  name: "Anu Jaakonsaari",
  password: "password",
  password_confirmation: "password",
  email: "anu.jaakonsaari@example.com",
  nationality: "finland",
  club: "kvks"
@juha_romppanen_finland = User.create!  name: "Juha Romppanen",
  password: "password",
  password_confirmation: "password",
  email: "juha.romppanen@example.com",
  nationality: "finland",
  club: "shs"
@anne_kiijarvi_finland = User.create!  name: "Anne Kiijärvi",
  password: "password",
  password_confirmation: "password",
  email: "anne.kiijärvi@example.com",
  nationality: "finland",
  club: "shs"
@agneta_henriksson_kiruna_sweden = User.create!  name: "Agneta Henriksson Kiruna,",
  password: "password",
  password_confirmation: "password",
  email: "agneta.henriksson.kiruna,@example.com",
  nationality: "sweden",
  club: "swe"
@anna_kristina_isoviita_finland = User.create!  name: "Anna-Kristina Isoviita",
  password: "password",
  password_confirmation: "password",
  email: "anna-kristina.isoviita@example.com",
  nationality: "finland",
  club: "shs"
@tero_asula_finland = User.create!  name: "Tero Asula",
  password: "password",
  password_confirmation: "password",
  email: "tero.asula@example.com",
  nationality: "finland",
  club: "l-svu"
@viktoria_ryytty_sphk_sweden = User.create!  name: "Viktoria Ryytty SPHK,",
  password: "password",
  password_confirmation: "password",
  email: "viktoria.ryytty.sphk,@example.com",
  nationality: "sweden",
  club: "swe"
@mika_hamari_finland = User.create!  name: "Mika Hamari",
  password: "password",
  password_confirmation: "password",
  email: "mika.hamari@example.com",
  nationality: "finland",
  club: "alma"
@sirkka_liisa_hamari_finland = User.create!  name: "Sirkka-Liisa Hamari",
  password: "password",
  password_confirmation: "password",
  email: "sirkka-liisa.hamari@example.com",
  nationality: "finland",
  club: "alma"
@niina_miettinen_finland = User.create!  name: "Niina Miettinen",
  password: "password",
  password_confirmation: "password",
  email: "niina.miettinen@example.com",
  nationality: "finland",
  club: "alma"
@eskil_knag_norway = User.create!  name: "Eskil Knag",
  password: "password",
  password_confirmation: "password",
  email: "eskil.knag@example.com",
  nationality: "norway",
  club: ""
@yngve_hoel_norway = User.create!  name: "Yngve Hoel",
  password: "password",
  password_confirmation: "password",
  email: "yngve.hoel@example.com",
  nationality: "norway",
  club: ""
@maurin_kerst_switzerland = User.create!  name: "Maurin Kerst",
  password: "password",
  password_confirmation: "password",
  email: "maurin.kerst@example.com",
  nationality: "switzerland",
  club: ""
@trond_are_hoel_norway = User.create!  name: "Trond Are Hoel",
  password: "password",
  password_confirmation: "password",
  email: "trond.are.hoel@example.com",
  nationality: "norway",
  club: ""
@adrian_meissner_switzerland = User.create!  name: "Adrian Meissner",
  password: "password",
  password_confirmation: "password",
  email: "adrian.meissner@example.com",
  nationality: "switzerland",
  club: ""
@yann_latrompette_france = User.create!  name: "Yann Latrompette",
  password: "password",
  password_confirmation: "password",
  email: "yann.latrompette@example.com",
  nationality: "france",
  club: ""
@mikael_lillestu_norway = User.create!  name: "Mikael Lillestu",
  password: "password",
  password_confirmation: "password",
  email: "mikael.lillestu@example.com",
  nationality: "norway",
  club: ""
@victor_carrasco_spain = User.create!  name: "Victor Carrasco",
  password: "password",
  password_confirmation: "password",
  email: "victor.carrasco@example.com",
  nationality: "spain",
  club: ""
@micael_pettersson_sweden = User.create!  name: "Micael Pettersson",
  password: "password",
  password_confirmation: "password",
  email: "micael.pettersson@example.com",
  nationality: "sweden",
  club: ""
@ludovic_coulaux_france = User.create!  name: "Ludovic Coulaux",
  password: "password",
  password_confirmation: "password",
  email: "ludovic.coulaux@example.com",
  nationality: "france",
  club: ""
@jonas_persson_sweden = User.create!  name: "Jonas Persson",
  password: "password",
  password_confirmation: "password",
  email: "jonas.persson@example.com",
  nationality: "sweden",
  club: ""
@jussi_pietikanen_finland = User.create!  name: "Jussi Pietikanen",
  password: "password",
  password_confirmation: "password",
  email: "jussi.pietikanen@example.com",
  nationality: "finland",
  club: ""
@kai_immonen_finland = User.create!  name: "Kai Immonen",
  password: "password",
  password_confirmation: "password",
  email: "kai.immonen@example.com",
  nationality: "finland",
  club: ""
@stephane_ettwiller_france = User.create!  name: "Stephane Ettwiller",
  password: "password",
  password_confirmation: "password",
  email: "stephane.ettwiller@example.com",
  nationality: "france",
  club: ""
@carina_aas_nilsen_norway = User.create!  name: "Carina Aas Nilsen",
  password: "password",
  password_confirmation: "password",
  email: "carina.aas.nilsen@example.com",
  nationality: "norway",
  club: ""
@kati_mansikkasalo_jurvelin_finland = User.create!  name: "Kati Mansikkasalo-Jurvelin",
  password: "password",
  password_confirmation: "password",
  email: "kati.mansikkasalo-jurvelin@example.com",
  nationality: "finland",
  club: ""
@tiina_blom_sweden = User.create!  name: "Tiina Blom",
  password: "password",
  password_confirmation: "password",
  email: "tiina.blom@example.com",
  nationality: "sweden",
  club: ""
@solveig_k_aaseby_norway = User.create!  name: "Solveig K. Aaseby",
  password: "password",
  password_confirmation: "password",
  email: "solveig.k..aaseby@example.com",
  nationality: "norway",
  club: ""
@Åsa_nordgren_sweden = User.create!  name: "Åsa Nordgren",
  password: "password",
  password_confirmation: "password",
  email: "Åsa.nordgren@example.com",
  nationality: "sweden",
  club: ""
@svetlana_muravskaya_russia = User.create!  name: "Svetlana Muravskaya",
  password: "password",
  password_confirmation: "password",
  email: "svetlana.muravskaya@example.com",
  nationality: "russia",
  club: ""
@heidi_kyyronen_finland = User.create!  name: "Heidi Kyyrönen",
  password: "password",
  password_confirmation: "password",
  email: "heidi.kyyrönen@example.com",
  nationality: "finland",
  club: ""
@corentin_coste_france = User.create!  name: "Corentin Coste",
  password: "password",
  password_confirmation: "password",
  email: "corentin.coste@example.com",
  nationality: "france",
  club: ""
@alexei_burashov_russia = User.create!  name: "Alexei Burashov",
  password: "password",
  password_confirmation: "password",
  email: "alexei.burashov@example.com",
  nationality: "russia",
  club: ""
@eira_aaseby_norway = User.create!  name: "Eira Aaseby",
  password: "password",
  password_confirmation: "password",
  email: "eira.aaseby@example.com",
  nationality: "norway",
  club: ""
@madelene_nord_sweden = User.create!  name: "Madelene Nord",
  password: "password",
  password_confirmation: "password",
  email: "madelene.nord@example.com",
  nationality: "sweden",
  club: ""
@oda_foss_almqvist_norway = User.create!  name: "Oda Foss Almqvist",
  password: "password",
  password_confirmation: "password",
  email: "oda.foss.almqvist@example.com",
  nationality: "norway",
  club: ""
@sanna_naslund_sweden = User.create!  name: "Sanna Näslund",
  password: "password",
  password_confirmation: "password",
  email: "sanna.näslund@example.com",
  nationality: "sweden",
  club: ""
@anna_kristine_amundrud_norway = User.create!  name: "Anna Kristine Amundrud",
  password: "password",
  password_confirmation: "password",
  email: "anna.kristine.amundrud@example.com",
  nationality: "norway",
  club: ""
@jonna_lipponen_finland = User.create!  name: "Jonna Lipponen",
  password: "password",
  password_confirmation: "password",
  email: "jonna.lipponen@example.com",
  nationality: "finland",
  club: ""
@tanja_ignatius_finland = User.create!  name: "Tanja Ignatius",
  password: "password",
  password_confirmation: "password",
  email: "tanja.ignatius@example.com",
  nationality: "finland",
  club: ""
@vera_ignatius_finland = User.create!  name: "Vera Ignatius",
  password: "password",
  password_confirmation: "password",
  email: "vera.ignatius@example.com",
  nationality: "finland",
  club: ""
@jørgen_mæland_sweden = User.create!  name: "Jørgen Mæland",
  password: "password",
  password_confirmation: "password",
  email: "jorgen.maland.com@example.com",
  nationality: "sweden",
  club: ""
@magnus_westerlund_sweden = User.create!  name: "Magnus Westerlund",
  password: "password",
  password_confirmation: "password",
  email: "magnus.westerlund@example.com",
  nationality: "sweden",
  club: ""
@mika_rainti_finland = User.create!  name: "Mika Rainti",
  password: "password",
  password_confirmation: "password",
  email: "mika.rainti@example.com",
  nationality: "finland",
  club: "alma"
@niina_konttaniemi_finland = User.create!  name: "Niina Konttaniemi",
  password: "password",
  password_confirmation: "password",
  email: "niina.konttaniemi@example.com",
  nationality: "finland",
  club: "rpkk"
@eeva_Äijala_finland = User.create!  name: "Eeva Äijälä",
  password: "password",
  password_confirmation: "password",
  email: "eeva.Äijälä@example.com",
  nationality: "finland",
  club: "avek"
@anu_ailinpieti_finland = User.create!  name: "Anu Ailinpieti",
  password: "password",
  password_confirmation: "password",
  email: "anu.ailinpieti@example.com",
  nationality: "finland",
  club: "kspk"
puts "Loaded #{User.count} users."