@roi_cross_sulanmaan__ds_km = @roi_cross_sulanmaan_.competitions.create! name: "DS1 4,5km",
  description: "DS1 Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__dcmw_km = @roi_cross_sulanmaan_.competitions.create! name: "DCMW 4,5km",
  description: "DCMW Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__dbm_dbw_km = @roi_cross_sulanmaan_.competitions.create! name: "DBM/DBW 4,5km",
  description: "DBM/DBW Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__dcmj_dcwj_km = @roi_cross_sulanmaan_.competitions.create! name: "DCMJ / DCWJ 3km",
  description: "DCMJ / DCWJ Men+Women Juniors 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__ds_j_km = @roi_cross_sulanmaan_.competitions.create! name: "DS1J 3km",
  description: "DS1J Men+Women Juniors 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__harr_ds_km = @roi_cross_sulanmaan_.competitions.create! name: "Harr. DS1 3km",
  description: "DS1 Men+Women Harrastus sarja 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__harr_dc_km = @roi_cross_sulanmaan_.competitions.create! name: "Harr. DC 3km",
  description: "DC Men+Women Harrastus sarja 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@robur_sprint__sp_km = @robur_sprint_.competitions.create! name: "Sp4 6km",
  description: "Sp4 Sprint 4 dog class 6km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "two races combined"
@robur_sprint__sp_km = @robur_sprint_.competitions.create! name: "Sp4 6km",
  description: "Sp4 Sprint 4 dog class 6km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "two races combined"
@robur_sprint__nms_km = @robur_sprint_.competitions.create! name: "NMS1 12km",
  description: "NMS 1 dog skiing men 12km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "single race"
@robur_sprint__nws_km = @robur_sprint_.competitions.create! name: "NWS1 12km",
  description: "NMS 1 dog skiing women 12km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "single race"
@ruuhirod__sp_x_km = @ruuhirod_.competitions.create! name: "Sp4 2 x 8km",
  description: "Ruuhisprint 4 dog class 2x8km",
  date_start: "2015-02-07",
  date_end: "2015-02-08",
  status: "open",
  format: "two races combined"
@ruuhirod__md_x_km = @ruuhirod_.competitions.create! name: "MD4 4 x 20km",
  description: "Middistance 4 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod__md_x_km = @ruuhirod_.competitions.create! name: "MD6 4 x 20km",
  description: "Middistance 6 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod__md_x_km = @ruuhirod_.competitions.create! name: "MD8 4 x 20km",
  description: "Middistance 8 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod__harr_kierros_km = @ruuhirod_.competitions.create! name: "Harr. kierros 20km",
  description: "Ruuhikierros 1x20km, koiramäärä min. 3 - max. 8",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_km = @ohkolan_talvi.competitions.create! name: "Sp4 12km",
  description: "Sprint 4 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_km = @ohkolan_talvi.competitions.create! name: "Sp4 12km",
  description: "Sprint 4 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_j_km = @ohkolan_talvi.competitions.create! name: "Sp4J 12km",
  description: "Sprint Juniori 4 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_j_km = @ohkolan_talvi.competitions.create! name: "Sp4J 12km",
  description: "Sprint Juniori 4 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_km = @ohkolan_talvi.competitions.create! name: "Sp6 12km",
  description: "Sprint 6 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_km = @ohkolan_talvi.competitions.create! name: "Sp6 12km",
  description: "Sprint 6 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_km = @ohkolan_talvi.competitions.create! name: "Sp1 3km",
  description: "Sprint 1 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_km = @ohkolan_talvi.competitions.create! name: "Sp2 3km",
  description: "Sprint 2 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp_j_km = @ohkolan_talvi.competitions.create! name: "Sp1J 3km",
  description: "Sprint Juniori 1 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@eastpoint_open_ = @eastpoint_open.competitions.create! name: "",
  description: "",
  date_start: "2015-02-13",
  date_end: "2015-02-15",
  status: "open",
  format: "single race"
@metsakartano_race_sm_sm_nmc_nwc_km = @metsakartano_race_sm.competitions.create! name: "SM NMC/NWC 16km",
  description: "NMD/NWC, NMCJ / NWCJ  Yhdistetyn SM kilpailut 2 x 8 km",
  date_start: "2014-02-15",
  date_end: "2014-02-15",
  status: "closed",
  format: "single race"
@metsakartano_race_sm_sm_sp_km = @metsakartano_race_sm.competitions.create! name: "SM Sp6 10 km",
  description: "SM Sp6, 6 koiran sprintti, 10 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_sm_sp_km = @metsakartano_race_sm.competitions.create! name: "SM Sp8 14,7 km",
  description: "SM Sp8, 8 koiran sprintti. 14,7 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_sp_km = @metsakartano_race_sm.competitions.create! name: "Sp4 7,2 km",
  description: "Sp4, 4 koiran sprintti. 7,2 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_spu_km = @metsakartano_race_sm.competitions.create! name: "SpU 21 km",
  description: "SpU, Avoin sprintti, 21 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_nms_km = @metsakartano_race_sm.competitions.create! name: "NMS2 10 km",
  description: "NSM2 2-koiran koirahiihto, miehet 10 km",
  date_start: "2014-02-16",
  date_end: "2014-02-16",
  status: "closed",
  format: "single race"
@metsakartano_race_sm_nws_km = @metsakartano_race_sm.competitions.create! name: "NWS2 10 km",
  description: "NSW2 2-koiran koirahiihto, naiset 10 km",
  date_start: "2014-02-16",
  date_end: "2014-02-16",
  status: "closed",
  format: "single race"
@_ifss_european_champ_sp_ = @_ifss_european_champ.competitions.create! name: "Sp4 7,2 + 7,2",
  description: "Sprint 4 dogs class, two races 7,2km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_sp_j_ = @_ifss_european_champ.competitions.create! name: "Sp4J 7,2 + 7,2",
  description: "Sprint Juniors 4 dogs class, two races 7,2km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_sp_ = @_ifss_european_champ.competitions.create! name: "Sp6 10 + 10",
  description: "Sprint 6 dogs class, two races 10km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_sp_ = @_ifss_european_champ.competitions.create! name: "Sp8 13 + 13",
  description: "Sprint 8 dogs class, two races 13km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_spu_ = @_ifss_european_champ.competitions.create! name: "SpU 21 + 21",
  description: "Sprint open dogs class, two races 21km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_md_ = @_ifss_european_champ.competitions.create! name: "MD12 41 + 41",
  description: "Mid-distance 12 dogs class, two races 41km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_md_ = @_ifss_european_champ.competitions.create! name: "MD6 41 + 41",
  description: "Mid-distance 6 dogs class, two races 41km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_nms_ = @_ifss_european_champ.competitions.create! name: "NMS1 8 + 8",
  description: "Nordic Sprint 1 Dog – Man 8 + 8km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nws_ = @_ifss_european_champ.competitions.create! name: "NWS1 8 + 5",
  description: "Nordic Sprint 1 Dog – Women 8 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nmsj_ = @_ifss_european_champ.competitions.create! name: "NMSJ 5 + 5",
  description: "Nordic Sprint 1 Dog - Man Juniours – Man 5 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nwsj_ = @_ifss_european_champ.competitions.create! name: "NWSJ 8 + 5",
  description: "Nordic Sprint 1 Dog – Women Juniors 5 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nwcj_ = @_ifss_european_champ.competitions.create! name: "NWCJ 5 + 5",
  description: "Nordic Combined 1 Dog – Women Juniors 5 + 5km",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nwc_ = @_ifss_european_champ.competitions.create! name: "NWC 7 + 7",
  description: "Nordic Combined 1 Dog – Women (2 + 5km) + (2 + 5km)",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nmc_ = @_ifss_european_champ.competitions.create! name: "NMC 7 + 7",
  description: "Nordic Combined 1 Dog – Men (2 + 5km) + (2 + 5km)",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@ruunaa_race_md_km = @ruunaa_race.competitions.create! name: "MD4 150km",
  description: "MD 4 dog class 3x50km",
  date_start: "2015-03-06",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@ruunaa_race_md_km = @ruunaa_race.competitions.create! name: "MD8 150km",
  description: "MD 8 dog class 3x50km",
  date_start: "2015-03-06",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp_km = @_taivalvaara_sled_do.competitions.create! name: "Sp4 8km",
  description: "Sprint 4 dog class 8km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp_j_km = @_taivalvaara_sled_do.competitions.create! name: "Sp4J 8km",
  description: "Sprint Juniori 4 dog class 8km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp_km = @_taivalvaara_sled_do.competitions.create! name: "Sp6 12km",
  description: "Sprint 6 dog class 12km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp_km = @_taivalvaara_sled_do.competitions.create! name: "Sp8 17km",
  description: "Sprint 8 dog class 17km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_spu_km = @_taivalvaara_sled_do.competitions.create! name: "SpU 17km",
  description: "Sprint Open class 21km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_harr_km = @_taivalvaara_sled_do.competitions.create! name: "Harr. 8km",
  description: "Harrastus sarja 8km",
  date_start: "2015-03-08",
  date_end: "2015-03-08",
  status: "open",
  format: "single race"
@_taivalvaara_sled_do_nms_ = @_taivalvaara_sled_do.competitions.create! name: "NMS1 8 + 8",
  description: "Nordic Sprint 1 Dog – Man 8 + 8km",
  date_start: "2015-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do_nws_ = @_taivalvaara_sled_do.competitions.create! name: "NWS1 8 + 5",
  description: "Nordic Sprint 1 Dog – Women 8 + 5km",
  date_start: "2015-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do_nmc_ = @_taivalvaara_sled_do.competitions.create! name: "NMC 7 + 7",
  description: "Nordic Combined 1 Dog – Men 7 + 7km, Mass Start",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do_nwc_ = @_taivalvaara_sled_do.competitions.create! name: "NWC 7 + 7",
  description: "Nordic Combined 1 Dog – Women 7 + 7km, Mass Start",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@shs_metsakartano_spr_sp_km = @shs_metsakartano_spr.competitions.create! name: "Sp4 8km",
  description: "Sprint 4 dog class 8km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_sp_j_km = @shs_metsakartano_spr.competitions.create! name: "Sp4J 8km",
  description: "Sprint Juniori 4 dog class 8km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_md_km = @shs_metsakartano_spr.competitions.create! name: "MD6 42km",
  description: "Mid distance 6 dog class 41km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_md_km = @shs_metsakartano_spr.competitions.create! name: "MD12 42km",
  description: "Mid distance 12 dog class 41km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_harr_km = @shs_metsakartano_spr.competitions.create! name: "Harr 8km",
  description: "Harrastus luokka 8km",
  date_start: "2015-03-15",
  date_end: "2015-03-15",
  status: "open",
  format: "single race"
@kuusamo_sprinti_sp_km = @kuusamo_sprinti.competitions.create! name: "Sp4 9km",
  description: "Epaviralinen Sprint 4 dog class 9km",
  date_start: "2015-03-28",
  date_end: "2015-03-28",
  status: "open",
  format: "single race"
@shs_metsakartano_spr_sp_km = @shs_metsakartano_spr.competitions.create! name: "Sp6 9+9km",
  description: "Sprint 6 dog class 9+9km",
  date_start: "2015-03-28",
  date_end: "2015-03-28",
  status: "open",
  format: "two races combined"
puts "Loaded a lot of competitions"