@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__ds_km",
  description: "DS1 Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__dcmw_km",
  description: "DCMW Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__dbm/dbw_km",
  description: "DBM/DBW Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__dcmj_/_dcwj_km",
  description: "DCMJ / DCWJ Men+Women Juniors 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__ds_j_km",
  description: "DS1J Men+Women Juniors 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__harr_ds_km",
  description: "DS1 Men+Women Harrastus sarja 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan_.competitions.create! name: "roi_cross_sulanmaan__harr_dc_km",
  description: "DC Men+Women Harrastus sarja 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@robur_sprint_.competitions.create! name: "robur_sprint__sp_km",
  description: "Sp4 Sprint 4 dog class 6km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "two races combined"
@robur_sprint_.competitions.create! name: "robur_sprint__sp_km",
  description: "Sp4 Sprint 4 dog class 6km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "two races combined"
@robur_sprint_.competitions.create! name: "robur_sprint__nms_km",
  description: "NMS 1 dog skiing men 12km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "single race"
@robur_sprint_.competitions.create! name: "robur_sprint__nws_km",
  description: "NMS 1 dog skiing women 12km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "single race"
@ruuhirod_.competitions.create! name: "ruuhirod__sp_x_km",
  description: "Ruuhisprint 4 dog class 2x8km",
  date_start: "2015-02-07",
  date_end: "2015-02-08",
  status: "open",
  format: "two races combined"
@ruuhirod_.competitions.create! name: "ruuhirod__md_x_km",
  description: "Middistance 4 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod_.competitions.create! name: "ruuhirod__md_x_km",
  description: "Middistance 6 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod_.competitions.create! name: "ruuhirod__md_x_km",
  description: "Middistance 8 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod_.competitions.create! name: "ruuhirod__harr_kierros_km",
  description: "Ruuhikierros 1x20km, koiramäärä min. 3 - max. 8",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_km",
  description: "Sprint 4 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_km",
  description: "Sprint 4 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_j_km",
  description: "Sprint Juniori 4 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_j_km",
  description: "Sprint Juniori 4 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_km",
  description: "Sprint 6 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_km",
  description: "Sprint 6 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_km",
  description: "Sprint 1 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_km",
  description: "Sprint 2 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi.competitions.create! name: "ohkolan_talvi_sp_j_km",
  description: "Sprint Juniori 1 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@eastpoint_open.competitions.create! name: "eastpoint_open_",
  description: "",
  date_start: "2015-02-13",
  date_end: "2015-02-15",
  status: "open",
  format: "single race"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_sm_nmc/nwc_km",
  description: "NMD/NWC, NMCJ / NWCJ  Yhdistetyn SM kilpailut 2 x 8 km",
  date_start: "2014-02-15",
  date_end: "2014-02-15",
  status: "closed",
  format: "single race"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_sm_sp_km",
  description: "SM Sp6, 6 koiran sprintti, 10 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_sm_sp_km",
  description: "SM Sp8, 8 koiran sprintti. 14,7 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_sp_km",
  description: "Sp4, 4 koiran sprintti. 7,2 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_spu_km",
  description: "SpU, Avoin sprintti, 21 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_nms_km",
  description: "NSM2 2-koiran koirahiihto, miehet 10 km",
  date_start: "2014-02-16",
  date_end: "2014-02-16",
  status: "closed",
  format: "single race"
@metsakartano_race_sm.competitions.create! name: "metsakartano_race_sm_nws_km",
  description: "NSW2 2-koiran koirahiihto, naiset 10 km",
  date_start: "2014-02-16",
  date_end: "2014-02-16",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_sp_+_",
  description: "Sprint 4 dogs class, two races 7,2km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_sp_j_+_",
  description: "Sprint Juniors 4 dogs class, two races 7,2km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_sp_+_",
  description: "Sprint 6 dogs class, two races 10km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_sp_+_",
  description: "Sprint 8 dogs class, two races 13km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_spu_+_",
  description: "Sprint open dogs class, two races 21km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_md_+_",
  description: "Mid-distance 12 dogs class, two races 41km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_md_+_",
  description: "Mid-distance 6 dogs class, two races 41km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nms_+_",
  description: "Nordic Sprint 1 Dog – Man 8 + 8km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nws_+_",
  description: "Nordic Sprint 1 Dog – Women 8 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nmsj_+_",
  description: "Nordic Sprint 1 Dog - Man Juniours – Man 5 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nwsj_+_",
  description: "Nordic Sprint 1 Dog – Women Juniors 5 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nwcj_+_",
  description: "Nordic Combined 1 Dog – Women Juniors 5 + 5km",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nwc_+_",
  description: "Nordic Combined 1 Dog – Women (2 + 5km) + (2 + 5km)",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ.competitions.create! name: "_ifss_european_champ_nmc_+_",
  description: "Nordic Combined 1 Dog – Men (2 + 5km) + (2 + 5km)",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@ruunaa_race.competitions.create! name: "ruunaa_race_md_km",
  description: "MD 4 dog class 3x50km",
  date_start: "2015-03-06",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@ruunaa_race.competitions.create! name: "ruunaa_race_md_km",
  description: "MD 8 dog class 3x50km",
  date_start: "2015-03-06",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_sp_km",
  description: "Sprint 4 dog class 8km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_sp_j_km",
  description: "Sprint Juniori 4 dog class 8km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_sp_km",
  description: "Sprint 6 dog class 12km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_sp_km",
  description: "Sprint 8 dog class 17km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_spu_km",
  description: "Sprint Open class 21km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_harr_km",
  description: "Harrastus sarja 8km",
  date_start: "2015-03-08",
  date_end: "2015-03-08",
  status: "open",
  format: "single race"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_nms_+_",
  description: "Nordic Sprint 1 Dog – Man 8 + 8km",
  date_start: "2015-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_nws_+_",
  description: "Nordic Sprint 1 Dog – Women 8 + 5km",
  date_start: "2015-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_nmc_+_",
  description: "Nordic Combined 1 Dog – Men 7 + 7km, Mass Start",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do.competitions.create! name: "_taivalvaara_sled_do_nwc_+_",
  description: "Nordic Combined 1 Dog – Women 7 + 7km, Mass Start",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@shs_metsakartano_spr.competitions.create! name: "shs_metsakartano_spr_sp_km",
  description: "Sprint 4 dog class 8km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr.competitions.create! name: "shs_metsakartano_spr_sp_j_km",
  description: "Sprint Juniori 4 dog class 8km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr.competitions.create! name: "shs_metsakartano_spr_md_km",
  description: "Mid distance 6 dog class 41km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr.competitions.create! name: "shs_metsakartano_spr_md_km",
  description: "Mid distance 12 dog class 41km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr.competitions.create! name: "shs_metsakartano_spr_harr_km",
  description: "Harrastus luokka 8km",
  date_start: "2015-03-15",
  date_end: "2015-03-15",
  status: "open",
  format: "single race"
@kuusamo_sprinti.competitions.create! name: "kuusamo_sprinti_sp_km",
  description: "Epaviralinen Sprint 4 dog class 9km",
  date_start: "2015-03-28",
  date_end: "2015-03-28",
  status: "open",
  format: "single race"
@shs_metsakartano_spr.competitions.create! name: "shs_metsakartano_spr_sp_+_km",
  description: "Sprint 6 dog class 9+9km",
  date_start: "2015-03-28",
  date_end: "2015-03-28",
  status: "open",
  format: "two races combined"
puts "Loaded a lot of competitions"