@roi_cross_sulanmaan__ds1_4_5km = @roi_cross_sulanmaan_.competitions.build name: "DS1 4,5km",
  description: "DS1 Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__dcmw_4_5km = @roi_cross_sulanmaan_.competitions.build name: "DCMW 4,5km",
  description: "DCMW Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__dbm_dbw_4_5km = @roi_cross_sulanmaan_.competitions.build name: "DBM/DBW 4,5km",
  description: "DBM/DBW Men+Women 4,5km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__dcmj_dcwj_3km = @roi_cross_sulanmaan_.competitions.build name: "DCMJ / DCWJ 3km",
  description: "DCMJ / DCWJ Men+Women Juniors 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__ds1j_3km = @roi_cross_sulanmaan_.competitions.build name: "DS1J 3km",
  description: "DS1J Men+Women Juniors 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__harr_ds1_3km = @roi_cross_sulanmaan_.competitions.build name: "Harr. DS1 3km",
  description: "DS1 Men+Women Harrastus sarja 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@roi_cross_sulanmaan__harr_dc_3km = @roi_cross_sulanmaan_.competitions.build name: "Harr. DC 3km",
  description: "DC Men+Women Harrastus sarja 3km",
  date_start: "2014-09-20",
  date_end: "",
  status: "closed",
  format: "single race"
@robur_sprint__sp4_6km = @robur_sprint_.competitions.build name: "Sp4 6km",
  description: "Sp4 Sprint 4 dog class 6km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "two races combined"
@robur_sprint__sp4_6km = @robur_sprint_.competitions.build name: "Sp4 6km",
  description: "Sp4 Sprint 4 dog class 6km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "two races combined"
@robur_sprint__nms1_12km = @robur_sprint_.competitions.build name: "NMS1 12km",
  description: "NMS 1 dog skiing men 12km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "single race"
@robur_sprint__nws1_12km = @robur_sprint_.competitions.build name: "NWS1 12km",
  description: "NMS 1 dog skiing women 12km",
  date_start: "2015-01-04",
  date_end: "",
  status: "open",
  format: "single race"
@ruuhirod__sp4_2_x_8km = @ruuhirod_.competitions.build name: "Sp4 2 x 8km",
  description: "Ruuhisprint 4 dog class 2x8km",
  date_start: "2015-02-07",
  date_end: "2015-02-08",
  status: "open",
  format: "two races combined"
@ruuhirod__md4_4_x_20km = @ruuhirod_.competitions.build name: "MD4 4 x 20km",
  description: "Middistance 4 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod__md6_4_x_20km = @ruuhirod_.competitions.build name: "MD6 4 x 20km",
  description: "Middistance 6 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod__md8_4_x_20km = @ruuhirod_.competitions.build name: "MD8 4 x 20km",
  description: "Middistance 8 dog class 4x20km",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ruuhirod__harr_kierros_20km = @ruuhirod_.competitions.build name: "Harr. kierros 20km",
  description: "Ruuhikierros 1x20km, koiramäärä min. 3 - max. 8",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp4_12km = @ohkolan_talvi.competitions.build name: "Sp4 12km",
  description: "Sprint 4 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp4_12km = @ohkolan_talvi.competitions.build name: "Sp4 12km",
  description: "Sprint 4 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp4j_12km = @ohkolan_talvi.competitions.build name: "Sp4J 12km",
  description: "Sprint Juniori 4 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp4j_12km = @ohkolan_talvi.competitions.build name: "Sp4J 12km",
  description: "Sprint Juniori 4 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp6_12km = @ohkolan_talvi.competitions.build name: "Sp6 12km",
  description: "Sprint 6 dog class 12km, day 1",
  date_start: "2015-02-07",
  date_end: "2015-02-07",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp6_12km = @ohkolan_talvi.competitions.build name: "Sp6 12km",
  description: "Sprint 6 dog class 12km, day 2",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp1_3km = @ohkolan_talvi.competitions.build name: "Sp1 3km",
  description: "Sprint 1 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp2_3km = @ohkolan_talvi.competitions.build name: "Sp2 3km",
  description: "Sprint 2 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@ohkolan_talvi_sp1j_3km = @ohkolan_talvi.competitions.build name: "Sp1J 3km",
  description: "Sprint Juniori 1 dog class 3km",
  date_start: "2015-02-08",
  date_end: "2015-02-08",
  status: "open",
  format: "single race"
@eastpoint_open_ = @eastpoint_open.competitions.build name: "",
  description: "",
  date_start: "2015-02-13",
  date_end: "2015-02-15",
  status: "open",
  format: "single race"
@metsakartano_race_sm_sm_nmc_nwc_16km = @metsakartano_race_sm.competitions.build name: "SM NMC/NWC 16km",
  description: "NMD/NWC, NMCJ / NWCJ  Yhdistetyn SM kilpailut 2 x 8 km",
  date_start: "2014-02-15",
  date_end: "2014-02-15",
  status: "closed",
  format: "single race"
@metsakartano_race_sm_sm_sp6_10_km = @metsakartano_race_sm.competitions.build name: "SM Sp6 10 km",
  description: "SM Sp6, 6 koiran sprintti, 10 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_sm_sp8_14_7_km = @metsakartano_race_sm.competitions.build name: "SM Sp8 14,7 km",
  description: "SM Sp8, 8 koiran sprintti. 14,7 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_sp4_7_2_km = @metsakartano_race_sm.competitions.build name: "Sp4 7,2 km",
  description: "Sp4, 4 koiran sprintti. 7,2 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_spu_21_km = @metsakartano_race_sm.competitions.build name: "SpU 21 km",
  description: "SpU, Avoin sprintti, 21 km",
  date_start: "2014-02-15",
  date_end: "2014-02-16",
  status: "closed",
  format: "two races combined"
@metsakartano_race_sm_nms2_10_km = @metsakartano_race_sm.competitions.build name: "NMS2 10 km",
  description: "NSM2 2-koiran koirahiihto, miehet 10 km",
  date_start: "2014-02-16",
  date_end: "2014-02-16",
  status: "closed",
  format: "single race"
@metsakartano_race_sm_nws2_10_km = @metsakartano_race_sm.competitions.build name: "NWS2 10 km",
  description: "NSW2 2-koiran koirahiihto, naiset 10 km",
  date_start: "2014-02-16",
  date_end: "2014-02-16",
  status: "closed",
  format: "single race"
@_ifss_european_champ_sp4_7_2_7_2 = @_ifss_european_champ.competitions.build name: "Sp4 7,2 + 7,2",
  description: "Sprint 4 dogs class, two races 7,2km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_sp4j_7_2_7_2 = @_ifss_european_champ.competitions.build name: "Sp4J 7,2 + 7,2",
  description: "Sprint Juniors 4 dogs class, two races 7,2km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_sp6_10_10 = @_ifss_european_champ.competitions.build name: "Sp6 10 + 10",
  description: "Sprint 6 dogs class, two races 10km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_sp8_13_13 = @_ifss_european_champ.competitions.build name: "Sp8 13 + 13",
  description: "Sprint 8 dogs class, two races 13km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_spu_21_21 = @_ifss_european_champ.competitions.build name: "SpU 21 + 21",
  description: "Sprint open dogs class, two races 21km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_md12_41_41 = @_ifss_european_champ.competitions.build name: "MD12 41 + 41",
  description: "Mid-distance 12 dogs class, two races 41km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_md6_41_41 = @_ifss_european_champ.competitions.build name: "MD6 41 + 41",
  description: "Mid-distance 6 dogs class, two races 41km each",
  date_start: "2014-03-08",
  date_end: "",
  status: "closed",
  format: "two races combined"
@_ifss_european_champ_nms1_8_8 = @_ifss_european_champ.competitions.build name: "NMS1 8 + 8",
  description: "Nordic Sprint 1 Dog – Man 8 + 8km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nws1_8_5 = @_ifss_european_champ.competitions.build name: "NWS1 8 + 5",
  description: "Nordic Sprint 1 Dog – Women 8 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nmsj_5_5 = @_ifss_european_champ.competitions.build name: "NMSJ 5 + 5",
  description: "Nordic Sprint 1 Dog - Man Juniours – Man 5 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nwsj_8_5 = @_ifss_european_champ.competitions.build name: "NWSJ 8 + 5",
  description: "Nordic Sprint 1 Dog – Women Juniors 5 + 5km",
  date_start: "2014-03-06",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nwcj_5_5 = @_ifss_european_champ.competitions.build name: "NWCJ 5 + 5",
  description: "Nordic Combined 1 Dog – Women Juniors 5 + 5km",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nwc_7_7 = @_ifss_european_champ.competitions.build name: "NWC 7 + 7",
  description: "Nordic Combined 1 Dog – Women (2 + 5km) + (2 + 5km)",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_ifss_european_champ_nmc_7_7 = @_ifss_european_champ.competitions.build name: "NMC 7 + 7",
  description: "Nordic Combined 1 Dog – Men (2 + 5km) + (2 + 5km)",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@ruunaa_race_md4_150km = @ruunaa_race.competitions.build name: "MD4 150km",
  description: "MD 4 dog class 3x50km",
  date_start: "2015-03-06",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@ruunaa_race_md8_150km = @ruunaa_race.competitions.build name: "MD8 150km",
  description: "MD 8 dog class 3x50km",
  date_start: "2015-03-06",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp4_8km = @_taivalvaara_sled_do.competitions.build name: "Sp4 8km",
  description: "Sprint 4 dog class 8km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp4j_8km = @_taivalvaara_sled_do.competitions.build name: "Sp4J 8km",
  description: "Sprint Juniori 4 dog class 8km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp6_12km = @_taivalvaara_sled_do.competitions.build name: "Sp6 12km",
  description: "Sprint 6 dog class 12km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_sp8_17km = @_taivalvaara_sled_do.competitions.build name: "Sp8 17km",
  description: "Sprint 8 dog class 17km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_spu_17km = @_taivalvaara_sled_do.competitions.build name: "SpU 17km",
  description: "Sprint Open class 21km",
  date_start: "2015-03-07",
  date_end: "2015-03-08",
  status: "open",
  format: "two races combined"
@_taivalvaara_sled_do_harr_8km = @_taivalvaara_sled_do.competitions.build name: "Harr. 8km",
  description: "Harrastus sarja 8km",
  date_start: "2015-03-08",
  date_end: "2015-03-08",
  status: "open",
  format: "single race"
@_taivalvaara_sled_do_nms1_8_8 = @_taivalvaara_sled_do.competitions.build name: "NMS1 8 + 8",
  description: "Nordic Sprint 1 Dog – Man 8 + 8km",
  date_start: "2015-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do_nws1_8_5 = @_taivalvaara_sled_do.competitions.build name: "NWS1 8 + 5",
  description: "Nordic Sprint 1 Dog – Women 8 + 5km",
  date_start: "2015-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do_nmc_7_7 = @_taivalvaara_sled_do.competitions.build name: "NMC 7 + 7",
  description: "Nordic Combined 1 Dog – Men 7 + 7km, Mass Start",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@_taivalvaara_sled_do_nwc_7_7 = @_taivalvaara_sled_do.competitions.build name: "NWC 7 + 7",
  description: "Nordic Combined 1 Dog – Women 7 + 7km, Mass Start",
  date_start: "2014-03-07",
  date_end: "",
  status: "closed",
  format: "single race"
@shs_metsakartano_spr_sp4_8km = @shs_metsakartano_spr.competitions.build name: "Sp4 8km",
  description: "Sprint 4 dog class 8km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_sp4j_8km = @shs_metsakartano_spr.competitions.build name: "Sp4J 8km",
  description: "Sprint Juniori 4 dog class 8km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_md6_42km = @shs_metsakartano_spr.competitions.build name: "MD6 42km",
  description: "Mid distance 6 dog class 41km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_md12_42km = @shs_metsakartano_spr.competitions.build name: "MD12 42km",
  description: "Mid distance 12 dog class 41km",
  date_start: "2015-03-14",
  date_end: "2015-03-15",
  status: "open",
  format: "two races combined"
@shs_metsakartano_spr_harr_8km = @shs_metsakartano_spr.competitions.build name: "Harr 8km",
  description: "Harrastus luokka 8km",
  date_start: "2015-03-15",
  date_end: "2015-03-15",
  status: "open",
  format: "single race"
@kuusamo_sprinti_sp4_9km = @kuusamo_sprinti.competitions.build name: "Sp4 9km",
  description: "Epaviralinen Sprint 4 dog class 9km",
  date_start: "2015-03-28",
  date_end: "2015-03-28",
  status: "open",
  format: "single race"
@shs_metsakartano_spr_sp6_9_9km = @shs_metsakartano_spr.competitions.build name: "Sp6 9+9km",
  description: "Sprint 6 dog class 9+9km",
  date_start: "2015-03-28",
  date_end: "2015-03-28",
  status: "open",
  format: "two races combined"
puts "Loaded a lot of competitions"